### ISSUE TITLE
networkx module version problem in Mash_based family finding

### ISSUE THREAD

**Issue by fantastycrane** [Magdoll/Cogent#18]
Hi, @Magdoll 

I installed Cogent using Anaconda recently and tested it with my own data. An error occured while running cmd in the bash file generated by generate_batch_cmd_for_Cogent_family_finding.py. Information is listed as follows.

"""
2.0
Expected output isoseq_flnc.fasta.s1000k30.dist already exists. Just use it.
making weight graph from  /share/nas1/yangch/test/Cogent/01.generate_bins/preCluster_out/1/isoseq_flnc.fasta.s1000k30.dist
graph contains 2 nodes, 1 edges
performing ncut on graph....
Traceback (most recent call last):
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/bin/process_kmer_to_graph.py", line 4, in <module>
    __import__('pkg_resources').run_script('Cogent==2.1', 'process_kmer_to_graph.py')
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1517, in run_script
    exec(code, namespace, namespace)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-2.1-py2.7.egg/EGG-INFO/scripts/process_kmer_to_graph.py", line 156, in <module>
    ncut_threshold=args.ncut_threshold)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-2.1-py2.7.egg/EGG-INFO/scripts/process_kmer_to_graph.py", line 78, in family_finding
    run_ncut(g, labels2_map, ncut_map, nodelist, ncut_threshold)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-2.1-py2.7.egg/EGG-INFO/scripts/process_kmer_to_graph.py", line 17, in run_ncut
    labels = np.array([i for i in G.nodes_iter()])
AttributeError: 'Graph' object has no attribute 'nodes_iter'
"""

It seems networkx-2.0 has removed the nodes_iter() method and now provides the the nodes() method instead. I replaced networkx-2.0 by installing networkx-1.11, but the same problem still happened. Any idea what might go wrong? Much appreciated!

**Comment by Magdoll** [comment]
Please downgrade to networkx-1.9 (I think 1.10 also work...guess not for 1.11).

You should be able to verify the networkx version will work if the following can be done:
```
>>> import networkx
>>> networkx.__version__
Out[5]: '1.9.1'
>>> x = networkx.Graph()
>>> x.add_edge(1, 2)
>>> x.degree().items()
Out[8]: [(1, 1), (2, 1)]
```

**Comment by fantastycrane** [comment]
My mistake. I did not downgrade networkx in anaCogent environment. The command works fine with version 1.11. Thanks.

**Comment by B10inform** [comment]
Hi Magdoll, 

I am getting following error with "process_kmer_to_graph.py ". networkx is version 2.5.

Traceback (most recent call last):
  File "/home/.conda/envs/anaCogent/bin/process_kmer_to_graph.py", line 4, in <module>
    __import__('pkg_resources').run_script('Cogent==6.1.0', 'process_kmer_to_graph.py')
  File "/home/.conda/envs/anaCogent/lib/python3.7/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/.conda/envs/anaCogent/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/home/.conda/envs/anaCogent/lib/python3.7/site-packages/Cogent-6.1.0-py3.7.egg/EGG-INFO/scripts/process_kmer_to_graph.py", line 155, in <module>
    ncut_threshold=args.ncut_threshold)
  File "/home/.conda/envs/anaCogent/lib/python3.7/site-packages/Cogent-6.1.0-py3.7.egg/EGG-INFO/scripts/process_kmer_to_graph.py", line 76, in family_finding
    for g in nx.connected_component_subgraphs(G):
AttributeError: module 'networkx' has no attribute 'connected_component_subgraphs'

Any help would be really great.

Thanks

**Comment by Magdoll** [comment]
Hi @B10inform ,
Cogent is currently working with networkx version 2.3. I think you may have to try a downgrade for now..
-Liz

**Comment by B10inform** [comment]
I downgraded networkx to v2.3. It is working. 
Thanks
